version: '2'
services:
  grafana:
    container_name:  grafana
    image: grafana/grafana-enterprise:8.2.0
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dashboards:/usr/share/grafana/public/dashboards
    environment: 
      - "GF_SECURITY_ADMIN_PASSWORD=123456"
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_SECRET_KEY=su2Tong2zoocie_"
    ports:
      - 3000:3000
