version: '3.3'
services:
  telegraf:
    container_name: telegraf
    restart: unless-stopped
    image: telegraf
    privileged: true
    volumes:
      - '/:/hostfs:ro'
      - '/run/udev:/run/udev:ro'
      - './etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - HOST_PROC=/hostfs/proc
      - TZ=Europe/Madrid
    networks:
      - i40sys
networks:
  i40sys:
    external:
      name: i40sys
