# Base image
FROM ubuntu:20.04

# Base
RUN apt update
RUN apt install python3 python3-pip -y


# Install the necessary Python packages
RUN pip3 install numpy matplotlib scipy scikit-image pickle5 tqdm hilbertcurve

