version: '3.3'
services:
  mqtt:
    container_name: mqtt
    ports:
      - '1883:1883'
        # - '9001:9001'
    volumes:
      - './etc/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro'
      - './etc/mqtt_users:/mosquitto/config/mqtt_users:ro'
      - './data:/mosquitto/data'
      - './log:/mosquitto/log'
    restart: unless-stopped
    image: eclipse-mosquitto
