version: "3.7"

services:
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=America
    volumes:
      - /dev:/host/dev
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    ports:
      - '1880:1880'
    healthcheck:
      test: ["CMD-SHELL","node /healthcheck.js"]
      interval: 60s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    privileged: true
