version: '3'

services:
  influxdb:
    image: influxdb:2.4.0-alpine
    env_file:
      - influxdb.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
volumes:
  influxdbv2:
